/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.5/samples
 */
plugins{
    application
    java
    id ("com.github.johnrengelman.shadow") version "8.1.1"
}


application {
    mainClass = "com.kuta.Main"
}


repositories{
    mavenCentral()
    gradlePluginPortal()
}

dependencies{
        implementation("com.google.code.gson:gson:2.10.1")
        testImplementation("org.junit.jupiter:junit-jupiter-api:5.8.1")
        implementation("mysql:mysql-connector-java:8.0.33")
        testRuntimeOnly ("org.junit.jupiter:junit-jupiter-engine:5.8.1")
}

tasks {
  withType<Jar> {
        manifest {
            attributes["Main-Class"] = "com.kuta.Main" 
        }
        configurations["compileClasspath"].forEach { file: File ->
        from(zipTree(file.absoluteFile))
    }
    }

    shadowJar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    archiveBaseName.set("alfa3")
    destinationDirectory.set(File("./"))
    mergeServiceFiles()
    manifest {
        attributes("Main-Class" to "com.kuta.Main")
    }
  }
}


tasks.named<Test>("test") {
    useJUnitPlatform()

    maxHeapSize = "1G"

    testLogging {
        events("passed")
    }
}
