DELIMITER //;
START TRANSACTION;

BEGIN;

insert into Doctor (fname, lname, started_practice) values ('Hersh', 'Yewen', '2006-07-29');
insert into Doctor (fname, lname, started_practice) values ('Izzy', 'Tringham', '1970-11-02');
insert into Doctor (fname, lname, started_practice) values ('Rafferty', 'McIlmurray', '1973-09-12');
insert into Doctor (fname, lname, started_practice) values ('Stormie', 'Stert', '1982-03-24');
insert into Doctor (fname, lname, started_practice) values ('Holden', 'Bruff', '1980-06-19');
insert into Doctor (fname, lname, started_practice) values ('Georg', 'Leuchars', '2001-12-21');
insert into Doctor (fname, lname, started_practice) values ('Humberto', 'Harrie', '1982-01-24');
insert into Doctor (fname, lname, started_practice) values ('Dominique', 'Vowden', '1994-02-08');
insert into Doctor (fname, lname, started_practice) values ('Mabel', 'Wardlaw', '2003-03-31');
insert into Doctor (fname, lname, started_practice) values ('Andie', 'Winterborne', '2001-08-06');
insert into Doctor (fname, lname, started_practice) values ('Giselbert', 'Rowly', '2012-06-14');
insert into Doctor (fname, lname, started_practice) values ('Mort', 'Stang-Gjertsen', '1997-08-06');
insert into Doctor (fname, lname, started_practice) values ('Shane', 'Stallan', '1992-12-15');
insert into Doctor (fname, lname, started_practice) values ('Heath', 'Durtnall', '1993-09-30');
insert into Doctor (fname, lname, started_practice) values ('Efrem', 'Brummell', '2020-11-13');
insert into Doctor (fname, lname, started_practice) values ('Maitilde', 'Dearlove', '1970-10-02');
insert into Doctor (fname, lname, started_practice) values ('Dulciana', 'Chaney', '1989-12-16');
insert into Doctor (fname, lname, started_practice) values ('Krysta', 'Dahle', '1995-10-09');
insert into Doctor (fname, lname, started_practice) values ('Corrina', 'Goney', '2020-06-30');
insert into Doctor (fname, lname, started_practice) values ('Lorelei', 'Manuello', '1976-09-18');
insert into Doctor (fname, lname, started_practice) values ('Raynor', 'Tanton', '1972-04-28');
insert into Doctor (fname, lname, started_practice) values ('Frasco', 'Remon', '2005-03-11');
insert into Doctor (fname, lname, started_practice) values ('Celesta', 'Doxey', '2020-08-29');
insert into Doctor (fname, lname, started_practice) values ('Stanleigh', 'Risbie', '1993-05-25');
insert into Doctor (fname, lname, started_practice) values ('Daffi', 'Clyburn', '1969-05-27');
insert into Doctor (fname, lname, started_practice) values ('Lyndel', 'Carman', '1998-04-30');
insert into Doctor (fname, lname, started_practice) values ('Judas', 'Wellbank', '2006-03-20');
insert into Doctor (fname, lname, started_practice) values ('Willette', 'Plumtree', '1998-03-05');
insert into Doctor (fname, lname, started_practice) values ('Corby', 'Schulter', '1994-06-30');
insert into Doctor (fname, lname, started_practice) values ('Glenden', 'MacMenemy', '1995-03-26');
insert into Doctor (fname, lname, started_practice) values ('Kiley', 'Matchett', '1982-11-02');
insert into Doctor (fname, lname, started_practice) values ('Krissie', 'Liston', '1986-10-04');
insert into Doctor (fname, lname, started_practice) values ('Dyanna', 'Zumbusch', '1987-11-09');
insert into Doctor (fname, lname, started_practice) values ('Jewelle', 'Saunderson', '1988-11-25');
insert into Doctor (fname, lname, started_practice) values ('Pammi', 'Etter', '1979-06-18');
insert into Doctor (fname, lname, started_practice) values ('Silvie', 'McGinty', '1989-09-18');
insert into Doctor (fname, lname, started_practice) values ('Ingar', 'De Roos', '1990-03-18');
insert into Doctor (fname, lname, started_practice) values ('Dal', 'Muir', '2008-11-26');
insert into Doctor (fname, lname, started_practice) values ('Lacie', 'Mytton', '2007-10-10');
insert into Doctor (fname, lname, started_practice) values ('Archaimbaud', 'Mate', '1969-11-17');
insert into Doctor (fname, lname, started_practice) values ('Fitzgerald', 'Vowell', '2017-01-27');
insert into Doctor (fname, lname, started_practice) values ('Kameko', 'Hillum', '1975-05-15');
insert into Doctor (fname, lname, started_practice) values ('Floria', 'Brea', '1996-10-13');
insert into Doctor (fname, lname, started_practice) values ('Jake', 'Porker', '1968-08-06');
insert into Doctor (fname, lname, started_practice) values ('Hendrika', 'Blewis', '1994-11-22');
insert into Doctor (fname, lname, started_practice) values ('Kamilah', 'Wilmington', '1984-09-18');
insert into Doctor (fname, lname, started_practice) values ('Koren', 'Houseley', '1967-05-30');
insert into Doctor (fname, lname, started_practice) values ('Margaretha', 'Legendre', '1989-06-01');
insert into Doctor (fname, lname, started_practice) values ('Rosella', 'Josefsson', '1989-01-20');
insert into Doctor (fname, lname, started_practice) values ('Yuri', 'Salvati', '1969-09-13');
insert into Doctor (fname, lname, started_practice) values ('Pattin', 'Fishbourn', '1983-01-04');
insert into Doctor (fname, lname, started_practice) values ('Alley', 'Atty', '2004-06-04');
insert into Doctor (fname, lname, started_practice) values ('Wrennie', 'Gumby', '2019-04-02');
insert into Doctor (fname, lname, started_practice) values ('Gerhardine', 'Jaspar', '1999-06-14');
insert into Doctor (fname, lname, started_practice) values ('Elyse', 'Tumioto', '2014-03-17');
insert into Doctor (fname, lname, started_practice) values ('Giacobo', 'Spiby', '2018-05-14');
insert into Doctor (fname, lname, started_practice) values ('Bibby', 'Orht', '2019-04-17');
insert into Doctor (fname, lname, started_practice) values ('Nike', 'Vanyarkin', '2017-06-27');
insert into Doctor (fname, lname, started_practice) values ('Sayre', 'Toffanelli', '1986-04-25');
insert into Doctor (fname, lname, started_practice) values ('Timmy', 'Urien', '1977-02-10');

END;
DELIMITER ;
